### ISSUE TITLE
Mention turning off the notifications will relieve one of needing the app symbol in the notification bar all day

### ISSUE THREAD

**Issue by jidanni** [antweb/SilentBoot#4]
On Google play, it says that one must live with having a notification permanently in the top of one's screen in order to use this program correctly. But that is not exactly the case on Android 12 at least. All one has to do is turn off the notifications or a  certain category notification for this app, and then I have still works perfectly, and one thus needs not have their top bar on the screen occupied by a symbol. Therefore you should mention that on Google play, and also inside the app somewhere. Thanks.

**Comment by jidanni** [comment]
![Screenshot_20220904-204112_Settings.jpg](https://user-images.githubusercontent.com/1230959/188340200-077e6d2f-a776-4cd6-a86a-80645fc9e7ae.jpg)

**Comment by antweb** [comment]
It's unfortunately not that easy. The notification is part of a Foreground Service that is needed to detect the shutdown broadcast intent. According to the [docs](https://developer.android.com/guide/components/foreground-services), the notification is strictly required to run such a Foreground Service on Android. 

What the docs do not mention though is what happens if the notification channel is disabled just like you describe. Given there is no information on how hiding the notification impacts the Foreground Service, I'm hesitant to recommend this. There is a decent chance that this will make it likelier for the service to be shut down by the system. Did you by any chance test this on other Android versions or devices from various manufacturers?

The proper solution for this is actually included in Android 13 with the [FGS Task Manager](https://developer.android.com/guide/components/foreground-services#handle-user-initiated-stop). I will give the FGS a try soon and add it information about it in the app / on the store listing.

**Comment by jidanni** [comment]
All I know is things have been working fine 98% of the boots.

There is a little message up there, but then it goes away 30 seconds after boot.

All I got is this one T-Mobile Samsung.

**Comment by antweb** [comment]
Closing this issue for now. Until I find more evidence that this works reliably across a majority of devices, the risk is too high. Will look into the Android 13 FGS Task Manager once more of my test devices received the update. 

Thank you for reporting your findings.
